# Generated by Django 4.0.4 on 2022-06-07 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_total_give_help_user_total_pmf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binarytree',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='binarytree',
            name='is_paid',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
