# Generated by Django 4.0.4 on 2022-06-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_paymentdetails_remove_binarytree_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='screenshotfile',
            field=models.ImageField(blank=True, null=True, upload_to='screenshotfile/'),
        ),
    ]
